[book]
title = "kuva"
description = "Scientific plotting library for Rust"
authors = ["James M. Ferguson"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/Psy-Fer/kuva"
edit-url-template = "https://github.com/Psy-Fer/kuva/edit/main/docs/src/{path}"
